# Generated by Django 3.2.12 on 2022-03-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
